### ISSUE TITLE
Show 'loading' when uploading a new SRG

### ISSUE THREAD

**Issue by rbclark** [mitre/vulcan#350] opened 2022-01-10 13:05 UTC
Currently when adding an SRG to the system there is a large delay between clicking 'Upload' and the request finishing. Having the button switch to a 'loading' button would help to alleviate any confusion the user may have.

**Comment by timwongj** [comment] 2022-05-18 05:58
Duplicate of: https://github.com/mitre/vulcan/issues/304

**Closed by timwongj** 2022-05-18 05:58 UTC
Labels: V3.0, enhancement, vmw
