### ISSUE TITLE
Configurable duplicate controls within an SRG

### ISSUE THREAD

**Issue by Bialogs** [mitre/vulcan#125] opened 2021-01-13 16:20 UTC
Vulcan allows you to mark a control within an SRG as a top-level/main control that fulfills the requirements of _n_ number of other controls. These other controls are then linked to the main control and hidden with a note that they are satisfied from the main, marked control.

**Comment by timwongj** [comment] 2021-11-01 15:41
this is a duplicate of https://github.com/mitre/vulcan/issues/285

**Closed by timwongj** 2021-11-01 15:41 UTC
Labels: V1.0
